sonarr:
  image: linuxserver/sonarr
  restart: always
  ports:
    - 8989:8989
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /dev/rtc:/dev/rtc:ro
    - /srv/Sonarr_config:/config:rw
    - /media/TvShows:/media/TvShows:rw
    - /media/Movies:/media/Movies

  environment:
    - PUID=1000
    - PGID=1000

nzbget:
  image: linuxserver/nzbget
  restart: always
  ports:
    - 6789:6789
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /dev/rtc:/dev/rtc:ro
    - /media/TvShows:/media/TvShows:rw
    - /media/Movies:/media/Movies:rw

  environment:
    - PUID=1000
    - PGID=1000

radarr:
  image: linuxserver/radarr
  restart: always
  ports:
    - 7878:7878
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /dev/rtc:/dev/rtc:ro
    - /srv/Radarr_config:/config:rw
    - /media/TvShows:/media/TvShows:rw
    - /media/Movies:/media/Movies:rw

  environment:
    - PUID=1000
    - PGID=1000
  restart: always


plexpy:
  image: linuxserver/plexpy
  volumes:
    - /srv/PlexPy_config:/datadir
  ports:
    - 8181:8181
  environment:
    - PUID=1000
    - PGID=1000
  restart: always

